name: Update Application
on:
  schedule:
    - cron: '0 0 * * 6' # at midnight every Saturday
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update saved time
        run: |
          python3 save_time.py
      - name: Configure rsconnect
        run: |
          rsconnect add --account ${{ vars.SHINYAPPS_USERNAME }} --name rsconnect-server --token ${{ secrets.SHINYAPPS_TOKEN }} --secret ${{ secrets.SHINYAPPS_SECRET }}
      - name: Deploy to rsconnect # app-id parameter allows reliable overwriting of app content without creating duplicate apps.
        run: |
          rsconnect deploy shiny --app-id ${{ secrets.APP_ID }} ./ --name rsconnect-server  --title scheduled-deployment
