name: Update Application
on:
    push
#   schedule:
#     - cron: '*/5 * * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update saved time
        run: |
          python3 save_time.py
      - name: Configure rsconnect
        run: |
          rsconnect add --account ${{ vars.RSCONNECT_USERNAME }} --name rsconnect-server --token ${{ secrets.RSCONNECT_TOKEN }} --secret ${{ secrets.RSCONNECT_SECRET }}
      - name: Deploy to rsconnect
        run: |
          rsconnect deploy shiny ./ --name rsconnect-server  --title test-schedule-deploy
          